import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

//components
import SideBar from "./components/SideBar";
import Footer from "./components/Footer";
import Header from "./components/Header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ModernFit Gym",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar />
        <div className="md:ml-64">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
